project_folder: 'results/'

params:
  binsize: 50000
  n_eigs: 128
  n_clusters: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 20, 32, 64]

assembly:
  name: hg38
  fasta_path: resources/hg38.fa

samples:
  H9:
    cooler_path: resources/4DNFIT5YVTLO.mcool
    blacklist_path: resources/h9.blacklist.bed

bigwig_metadata_path: config/track_metadata.tsv

tracks:
  cluster:
    type: "category"
  chrom:
    type: "category"
  GC:
    type: "divergent"
    options:
      cmap: "RdYlBu_r"
      vmin: 0.35
      vmax: 0.65
  centel_abs:
    type: "scalar"
    options:
      cmap: "Greys"
      vmin: 0
      vmax: 149043529
  H2AK5ac:
    type: "scalar"
  H2BK12ac:
    type: "scalar"
  H2BK15ac:
    type: "scalar"

heatmap_groups:
  required:
    - centel_abs
    - GC
  chip:
    - H2AK5ac
    - H2BK12ac
    - H2BK15ac

scatter_groups:
  all:
    - centel_abs
    - GC
    - H2AK5ac
    - H2BK12ac
    - H2BK15ac
