dependencies:
  - python=3.9
  - pip
  - cython
  - numpy
  - h5py
  - ipython
  - bioconda::bedtools
  - bioconda::ucsc-bedgraphtobigwig
  - bioconda::ucsc-bigwigtobedgraph
  - pip:
<<<<<<< HEAD
    - bioframe==0.2.*
=======
    - bioframe==0.3.*
>>>>>>> agalitsyna/master
    - cooltools==0.5.*
    - cooler
    - datashader
    - ipympl
    - ipdb
    - jupyterlab
    - loky
    - matplotlib==3.4.*
    - pandas
    - pyarrow
    - pybbi
    - pysam
    - scikit-learn
    - scipy
    - seaborn
    - snakemake
    - tqdm
    - -e ./
